name: list and test
on: 
    push:              # pushing to the main branch will trigger this workflow
        branches:
            - master
        paths-ignore:
        - '.github/workflows/*'     
    pull_request:      # opening a pull request will trigger this workflow
        types:
            - opened       
jobs:
    linting:
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkout@v4
            - name: install dependencies
              run: npm ci
            - name: run linting
              run: npm run lint
    testing:
        needs: linting
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkout@v4
            - name: install dependencies
              run: npm ci
            - name: run testing
              run: npm run test                     
            

            