name: list and test
on: 
    # push:              # pushing to the main branch and also not change anything in the 'github/workflows/*' will trigger this workflow
    #     branches:
    #         - master
        # paths-ignore:  
        # - '.github/workflows/*'     
    pull_request:      # opening a pull request will trigger this workflow
        types:
            - opened       
jobs:
    linting:
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkout@v4
            - name: Caching
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: cache-node-${{hashFiles('**/package-lock.json')}}  
            - name: install dependencies
              run: npm ci
            - name: run linting
              run: npm run lint
    testing:
        needs: linting
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkout@v4
            - name: Caching
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: cache-node-${{hashFiles('**/package-lock.json')}}  
            - name: install dependencies
              run: npm ci
            - name: run testing
              run: npm run test
    building:
      needs: testing
      runs-on: ubuntu-latest
      steps:
        - name: get code
          uses: actions/checkout@v4
        - name: Caching
          uses: actions/cache@v4
          with:
            path: ~/.npm
            key: cache-node-${{hashFiles('**/package-lock.json')}}  
        - name: install dependencies
          run: npm ci
        - name: build
          run: npm run build
        - name: upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: my-artifacts      #name of the artifact
            path: dist              #artifact will be found in this directory
    
    deploy:
      needs: building
      runs-on: ubuntu-latest
      steps:
        - name: get code
          uses: actions/checkout@v4
        - name: get artifacts
          uses: actions/download-artifact@v4
          with:
            name: my-artifacts     #donwload artifacts named my-artifacts
        - name: view everything in the current directory including artifacts
          run : ls                   #listing all the files in the current directory
        - name: deployment
          run: echo "other deployment steps...."   

            