name: commands running
on: push
jobs:
    commands:
        runs-on: ubuntu-latest
        steps:
            - name: get the code
              uses: actions/checkout@v4
            - name: linux commands running
              run: |
                 echo "print current directory"
                 pwd
                 echo "print all files and folders"
                 ls -la
                 cd src/test
                 echo "print current directory"
                 pwd
                 echo "print all contents"
                 ls 


        